baseURL = 'https://odhyp.com/'
title = 'Odhy Pradhana'
languageCode = 'en-us'
defaultContentLanguage = "en"
enableRobotsTXT = true

# SEO Optimization
[params]
author = { name = "Odhy Pradhana", email = "hello@odhyp.com" }
description = "Personal website about automation, data visualization, and web development."

# Custom taxonomies
[taxonomies]
topic = "topics"
tech_stack = "tech_stacks"

# Markup highlighting & ToC configuration
[markup]
[markup.highlight]
style = "monokai"
tabWidth = 4
[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true

# Minify HTML, CSS, and JS for better performance
[minify]
minifyOutput = true

# Sitemap Configuration (Taxonomy and Term are currently disabled)
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]

# Sitemap
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Builds (TailwindCSS)
[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'

# Modules (TailwindCSS)
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'
