baseURL = 'https://odhyp.github.io/'
languageCode = 'en-us'
title = 'Odhy'

# Author information
[params]
  author = "Odhy Pradhana"
  authorLink = "https://yourwebsite.com/"
  description = "Portfolio and Blog website"
  socialGithub = "https://github.com/odhyp"
  socialTwitter = "https://twitter.com/name"
  socialLinkedIn = "https://linkedin.com/in/name"

# Hugo Module version requirement
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

# Git Info for Last Modify Date
enableGitInfo = true

# Site Menus
[[menus.main]]
name = 'Projects'
pageRef = '/project'
weight = 20

[[menus.main]]
name = 'Blogs'
pageRef = '/blog'
weight = 30

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 40

# Markup highlighting configuration
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-dark'
    tabWidth = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
