baseURL = 'https://odhyp.com/'
languageCode = 'en-us'
title = 'Odhy Pradhana'

[params.author]
name = "Odhy Pradhana"
email = "pradhana.odhy@gmail.com"

# Custom taxonomies
[taxonomies]
category = "categories"
tag = "tags"

# Markup highlighting configuration
[markup]
[markup.highlight]
style = "onedark"
tabWidth = 4
[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true