baseURL = 'https://odhyp.com/'
title = 'Odhy Pradhana'
languageCode = 'en-us'
defaultContentLanguage = "en"

# SEO Optimization
[params]
author = "Odhy Pradhana"
description = "Personal website about automation, data visualization, and web development."
google_site_verification = "YOUR_VERIFICATION_CODE"

# Custom taxonomies
[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
projects = "/projects/:slug/"
writings = "/writings/:slug/"

# Markup highlighting configuration
[markup]
[markup.highlight]
style = "onedark"
tabWidth = 4
[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true

# Minify HTML, CSS, and JS for better performance
[minify]
minifyOutput = true

# Robots.txt Configuration
[outputs]
home = ["html", "rss", "json", "sitemap", "robots"]

# Sitemap Configuration 
[sitemap]
changefreq = "monthly"
priority = 0.8

# Enable Google Analytics
[services]
[services.googleAnalytics]
id = "UA-XXXXXXXXX-X" # Replace with actual tracking ID
