baseURL = 'https://odhyp.vercel.app/'
languageCode = 'en-us'
title = 'Odhy'
theme = 'odai-theme'

# Author information
[params]
  author = "Odhy Pradhana"
  authorLink = "https://yourwebsite.com/"
  description = "Portfolio and Blog website"
  socialGithub = "https://github.com/odhyp"
  socialTwitter = "https://twitter.com/valgtreiz"
  socialLinkedin = "https://linkedin.com/in/odhy-pradhana"
  socialEmail = "pradhana.odhy@gmail.com"

# Hugo Module version requirement
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

# Git Info for Last Modify Date
enableGitInfo = true

# Markup highlighting configuration
[markup]
  [markup.highlight]
    style = "catppuccin-macchiato"
