baseURL = 'https://odhyp.com/'
languageCode = 'en-us'
title = 'Odhy'
enableGitInfo = true

# Hugo Module version
[module]
  [module.hugoVersion]
    extended = true
    min = "0.133.1"

# Markup highlighting configuration
[markup]
  [markup.highlight]
    style = "monokai"
    tabWidth = 4
