baseURL = 'https://odhyp.com/'
languageCode = 'en-us'
title = 'Odhy'

# Custom taxonomies
[taxonomies]
category = "categories"
tag = "tags"

# Markup highlighting configuration
[markup]
[markup.highlight]
style = "monokai"
tabWidth = 4
[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true
[markup.goldmark.renderer]
unsafe = true
