baseURL = 'https://odhyp.vercel.app/'
languageCode = 'en-us'
title = 'Odhy'
theme = 'odai-theme'
enableGitInfo = true

# Page custom parameters
[Params]
  description = "Portfolio and Blog website"
  disableComments = false
  giscusTheme = "dark"

# Author information
[Params.Author]
  fullname = "Odhy Pradhana"
  shortname = "Odhy"
  bio = "A Python Developer"
  avatar = "https://i.pinimg.com/736x/49/3c/a1/493ca1e393a923bc04a1293f7ea76873.jpg"

# Social account info
[Params.Social]
  email = "pradhana.odhy@gmail.com"
  github = "https://github.com/odhyp"
  linkedin = "https://linkedin.com/in/odhy-pradhana"
  facebook = ""
  twitter = "https://twitter.com/valgtreiz"
  instagram = ""
  medium = ""

# Hugo Module version
[module]
  [module.hugoVersion]
    extended = true
    min = "0.133.1"

# Markup highlighting configuration
[markup]
  [markup.highlight]
    style = "monokai"
    tabWidth = 4

# Custom taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
